name: api-deploy

on:
  # Triggers the workflow on push request event but only for the "master" branch
  workflow_dispatch:
  push:
    branches: ["master"]

permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker-deploy:
    name: Docker Deploy
    runs-on: ubuntu-latest

    env:
      AWS_ECR_REPO: listopia-parser

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.AWS_ECR_REPO }} .

      - name: Configure AWS Credentials for github actions
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}

      - name: Docker Login
        run: |
          aws ecr get-login-password \
              --region ${{ secrets.AWS_REGION }} \
          | docker login \
              --username AWS \
              --password-stdin ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Docker Push
        run: docker push ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.AWS_ECR_REPO }}

  tf-apply:
    # The type of runner that the job will run on
    name: Terraform apply
    runs-on: ubuntu-latest
    needs: docker-deploy

    defaults:
      run:
        working-directory: terraform/

    env:
      ENVIRONMENT: prod
      TF_CLOUD_PROJECT: ByItsCover_PROD
      TF_WORKSPACE: bic-embed-server-prod

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Hashicorp - Terraform setup
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Runs a set of terraform commands using the runners shell
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: |
          terraform fmt -recursive
          terraform validate
        continue-on-error: false

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=variables/${{ env.ENVIRONMENT }}.tfvars
