name: app-deploy

on:
  workflow_dispatch:
  push:
    branches: ["master"]

permissions:
  id-token: write
  contents: read

jobs:
  check-changes:
    name: Check for Changes
    runs-on: ubuntu-latest

    outputs:
      should_deploy: ${{ steps.filter.outputs.src }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Paths Filter
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - '**'
              - '!terraform/**'
              - '!**.md'

  docker-deploy:
    name: Docker Deploy
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.should_deploy == 'true'

    env:
      AWS_ECR_REPO: listopia-parser

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build --platform linux/arm64 -t ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.AWS_ECR_REPO }} .

      - name: Configure AWS Credentials for github actions
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}

      - name: Docker Login
        run: |
          aws ecr get-login-password \
              --region ${{ secrets.AWS_REGION }} \
          | docker login \
              --username AWS \
              --password-stdin ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Docker Push
        run: docker push ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.AWS_ECR_REPO }}

  tf-apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    needs: docker-deploy
    if: ${{ always() && !failure() && !cancelled() }}

    defaults:
      run:
        working-directory: terraform/

    env:
      ENVIRONMENT: prod
      TF_CLOUD_PROJECT: ByItsCover_PROD
      TF_WORKSPACE: bic-listopia-parser-prod
      TF_VAR_hardcover_api_key: secrets.HARDCOVER_API_KEY

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Hashicorp - Terraform setup
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: |
          terraform fmt -recursive
          terraform validate
        continue-on-error: false

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=variables/${{ env.ENVIRONMENT }}.tfvars
