name: terraform-apply

on:
  # Triggers the workflow on push request event but only for the "master" branch
  workflow_dispatch:
  push:
    branches: ["master"]

permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  apply:
    # The type of runner that the job will run on
    name: Terraform apply
    runs-on: ubuntu-latest
    environment: ByItsCover-Dev

    env:
      variable-file: variables/prod.tfvars
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

    defaults:
      run:
        working-directory: infra/

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Hashicorp - Terraform setup
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}

      # Runs a set of terraform commands using the runners shell
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: |
          terraform fmt -recursive
          terraform validate
        continue-on-error: false

      - name: Terraform Apply
        run: terraform apply -var-file=${{ env.variable-file }}
