name: terraform-plan

on:
  # Triggers the workflow on push request event but only for the "master" branch
  workflow_dispatch:
  push:
    branches: ["master"]

  pull_request:
    branches: ["master"]

permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  plan:
    # The type of runner that the job will run on
    name: Terraform plan
    runs-on: ubuntu-latest
    environment: ByItsCover-Dev

    env:
      variable-file: variables/prod.tfvars
      TF_API_TOKEN: ${{secrets.TF_API_TOKEN}}

    defaults:
      run:
        working-directory: infra/

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20

      - name: Hashicorp - Terraform setup
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          cli_config_credentials_token: $TF_API_TOKEN

      # Runs a set of terraform commands using the runners shell
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: |
          terraform fmt -recursive
          terraform validate
        continue-on-error: false

      - name: Terraform Plan
        run: terraform plan -var-file=$variable-file
